name: Build and Deploy Back End Service

on:
  workflow_call:
    inputs:
      git-ref:
        description: The ref to pull down and build
        required: false
        type: string
        default: ${{ github.ref }}
    secrets:
      packages-read-token:
        description: A token with access to pull packages from TBOL registry
        required: true
      aws-access-key-id:
        description: AWS access key id
        required: true
      aws-secret-access-key:
        description: AWS access key secret
        required: true
      aws-region:
        description: AWS region
        required: true

jobs:
  build-and-deploy:
    name: Build and Deploy Back End Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./okta-authorizer

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.git-ref }}

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: "@tbol-com"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ secrets.aws-region }}

      - name: Echo Lambda function name
        run: echo "Lambda function name is ${{ env.LAMBDA_FUNCTION_NAME }}"

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.packages-read-token }}

      - name: Run build
        run: yarn build

      - name: Run lint
        run: yarn lint

      - name: Run test
        run: yarn test

      - name: Install dependencies for deployment
        run: |
          cd ./dist
          yarn install --production
        env:
          NODE_AUTH_TOKEN: ${{ secrets.packages-read-token }}
          CI: true

      - name: Deploy Lambda function
        run: |
          cd ./dist
          zip -r -D deploy.zip * >/dev/null
          aws lambda update-function-code --function-name=okta-authorizer-lambda --zip-file=fileb://deploy.zip
