name: Build and Deploy Back End Service

on:
  workflow_call:
    inputs:
      git-ref:
        description: The ref to pull down and build
        required: false
        type: string
        default: ${{ github.ref }}
    secrets:
      packages-read-token:
        description: A token with access to pull packages from TBOL registry
        required: true
      aws-ecr-registry:
        description: AWS ECR Registry
        required: true
      aws-access-key-id:
        description: AWS access key id
        required: true
      aws-secret-access-key:
        description: AWS access key secret
        required: true

jobs:
  build-and-deploy:
    name: Build and Deploy Back End Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.git-ref }}

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: "@tbol-com"

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.packages-read-token }}

      - name: Run build
        run: yarn build

      - name: Run lint
        run: yarn lint

      - name: Run test
        run: yarn test

      - name: "Create .npmrc file"
        run: |
          echo '@tbol-com:registry=https://npm.pkg.github.com' > ${{ github.workspace }}/.npmrc
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.packages-read-token }}' >> ${{ github.workspace }}/.npmrc

      - name: Login to Amazon ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.aws-ecr-registry }}
          username: ${{ secrets.aws-access-key-id }}
          password: ${{ secrets.aws-secret-access-key }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: "${{ secrets.aws-ecr-registry }}/${{ github.event.repository.name }}:${{ github.sha }}"
          push: true
          secret-files: |
            "npm=${{ github.workspace }}/.npmrc"
